title: "@mestvya's Notes"
description: This is a site for documenting.
theme: just-the-docs

url: /

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

color_scheme: dark
